Add confirm to continue if not staged changes when commiting.

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -14,8 +14,16 @@ if ! git diff --quiet; then
   echo "👉 Did you forget to save files in your editor?"
   echo "👉 Run: git add -A"
   echo ""
-  echo "❌ Commit aborted."
-  exit 1
+  read -p "Continue anyway? (y/N): " CONFIRM </dev/tty
+  case "$CONFIRM" in
+    [Yy]* )
+      echo "✅ Continuing..."
+      ;;
+    * )
+      echo "❌ Commit aborted."
+      exit 1
+      ;;
+  esac
 fi
 
 # -----------------------------
@@ -78,6 +86,7 @@ if [ "$BRANCH" = "main" ]; then
   echo "git checkout main"
   echo "git merge feature/my-feature"
   echo ""
+  echo "test"
 
   # Force interactive terminal input
   read -r -p "Continue? (y/N): " CONFIRM </dev/tty
